### ISSUE TITLE
externally tagged enums

### ISSUE THREAD

**Issue by dherman** [toml-rs/toml-rs#225]
When you define an enum and derive `Serialize` or `Deserialize`, you might expect it to get the ["externally tagged"](https://serde.rs/enum-representations.html) semantics described by the serde documentation -- where each variant is represented as a table with a key named after the variant name. But AFAICT this representation doesn't work. Here's a simple example, a config format with a `[main]` section and a `plugin` field that can be one of `{ "url" = ...}` or `{ "bin" = ... }`:

```rust
extern crate toml;
#[macro_use]
extern crate serde_derive;
extern crate serde;

#[derive(Serialize, Deserialize, Debug)]
pub struct Config {
    pub main: Option<Main>
}

#[derive(Serialize, Deserialize, Debug)]
#[serde(rename = "main")]
pub struct Main {
    pub plugin: Option<Plugin>,
}

#[derive(Serialize, Deserialize, Debug)]
#[serde(rename_all = "lowercase")]
pub enum Plugin {
    Url(String),
    Bin(String)
}

const SRC: &'static str = "
[main]
plugin = { \"bin\" = \"echo 'hello'\" }
";

fn main() {
    match toml::from_str::<Config>(SRC) {
        Err(e) => { eprintln!("error: {}", e); }
        Ok(result) => { eprintln!("result: {:?}", result); }
    }

}
```

This fails to deserialize at runtime with the error "expected string for key `main.plugin`". I'm not sure why.

BTW there are workarounds, e.g. to use the untagged representation:

```rust
extern crate toml;
#[macro_use]
extern crate serde_derive;
extern crate serde;

#[derive(Serialize, Deserialize, Debug)]
pub struct Config {
    pub main: Option<Main>
}

#[derive(Serialize, Deserialize, Debug)]
#[serde(rename = "main")]
pub struct Main {
    pub plugin: Option<Plugin>,
}

#[derive(Serialize, Deserialize, Debug)]
#[serde(untagged)]
pub enum Plugin {
    Url { url: String },
    Bin { bin: String }
}

const SRC: &'static str = "
[main]
plugin = { \"bin\" = \"echo 'hello'\" }
";

fn main() {
    match toml::from_str::<Config>(SRC) {
        Err(e) => { eprintln!("error: {}", e); }
        Ok(result) => { eprintln!("result: {:?}", result); }
    }

}
```

**Comment by azriel91** [comment]
Hiya, so I ran into these use cases in one of my projects, and was wondering if you think this type of usage pattern should be accepted:

For the given types:

```rust
#[derive(Debug, Deserialize)]
struct Config {
    plain: MyEnum,
    // tuple: MyEnum,
    #[serde(rename = "struct")]
    structv: MyEnum,
    my_enum: Vec<MyEnum>,
}

#[derive(Debug, Deserialize)]
enum MyEnum {
    Plain,
    Tuple(i64, bool),
    Struct { value: i64 },
}
```

Accept the following:

```toml
plain = "Plain"
tuple = { 0 = 123, 1 = true }
struct = { Struct = { value = 123 } }
my_enum = [
    { Plain = {} },
    { Tuple = { 0 = 123, 1 = true } },
    { Struct = { value = 123 } }
]
```

So far this is what I've got:

```toml
# toml
my_enum = "UnitVariant"                             # works with current toml crate
my_enum = { UnitVariant = {} }                      # implemented on #264
my_enum = { StructVariant = { field = "value" } }   # implemented on #264
my_enum = { TupleVariant = [123, false] }           # invalid TOML
my_enum = { TupleVariant = { 0 = 123, 1 = false } } # what I am trying to implement
```
