### ISSUE TITLE
Doc improvements needed around parsing unknown table names

### ISSUE THREAD

**Issue by kallisti5** [toml-rs/toml-rs#247]
None of the docs seem to show how to handle parsing unknown / dynamic toml tables.

```toml
[ThingA]
url = "magic"
test = false

[ThingB]
url = "magicb"
test = true
```

Forming a struct around this seems like the best way (url and test are consistent keys) but no examples or documentation around capturing the unknown "ThingA" vs "ThingB"
