### ISSUE TITLE
Update dotted key handling between tables.

### ISSUE THREAD

**Issue by ehuss** [toml-rs/toml-rs#323]
There are some new clarifications in the spec on how dotted keys interact with other tables.  The following two PRs are relevant:

https://github.com/toml-lang/toml/pull/652  (I believe toml-rs already handles this)
https://github.com/toml-lang/toml/pull/655

In particular, the example from 655 does not parse (reported from @samuelcolvin):

The following TOML is [included in the main toml docs as valid](https://github.com/toml-lang/toml#table)

```toml
[fruit]
apple.color = "red"
apple.taste.sweet = true

[fruit.apple.texture]  # you can add sub-tables
smooth = true
```

But gives the error

    duplicate key: `apple` for key `fruit` at line 5 column 1

When parsed with toml-rs.
