### ISSUE TITLE
Failure to deserialize externally tagged enums from dotted keys

### ISSUE THREAD

**Issue by unneon** [toml-rs/toml-rs#350]
Trying to deserialize a dotted key as an enum variant returns an error. For example, deserialization of `pet.Kitty = {}` fails, and `pet = { Kitty = {} }`(or a different enum form) has to be used instead. This is rather inconvenient when dealing with nested enums, e.g.:
```toml
[axes]
move_vertical.Emulated = { pos.Key = "W", neg.Key = "S" }
move_horizontal.Emulated = { pos.Key = "D", neg.Key = "A" }
```
has to be replaced with:
```toml
[axes]
move_vertical = { Emulated = { pos = { Key = "W" }, neg = { Key = "S" } } }
move_horizontal = { Emulated = { pos = { Key = "D" }, neg = { Key = "A" } } }
```

A minimal test case can look like this:
```rust
#[derive(Debug, serde::Deserialize)]
enum Cute {
    Kitty,
    Hamster,
}
#[derive(Debug, serde::Deserialize)]
struct Room {
    pet: Cute,
}

fn main() {
    let parsed_1 = toml::from_str::<Room>("pet = \"Kitty\"");
    let parsed_2 = toml::from_str::<Room>("pet = { Kitty = {} }");
    let parsed_3 = toml::from_str::<Room>("[pet.Kitty]");
    let parsed_4 = toml::from_str::<Room>("pet.Kitty = {}");
    let _ = dbg!(parsed_1);
    let _ = dbg!(parsed_2); 
    let _ = dbg!(parsed_3); // does work on master
    let _ = dbg!(parsed_4); // does not work
}
```
