### ISSUE TITLE
Inconsistent deserialization-serialization with root structs

### ISSUE THREAD

**Issue by Nachasic** [toml-rs/toml-rs#398]
When deserializing a struct that we got by serializing a toml, it might not include global fields, depending on the way they were described in the original toml.

Given toml:
```toml
[machine]
    name = "Sample text"
    
    [[activity]]
        name = "TOML FTW"
        property = 1
```
and definitions in rust:
```rust
#[derive(Debug, Serialize, Deserialize)]
pub struct Substruct {
    name: Option<String>,
    property: Option<i8>,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct Machine {
    name: Option<String>,
    activity: Option<Vec<Substruct>>
}
```
I get an instance of `Machine` using `toml::from_str` and then serializing it back using `toml::to_string` (or `toml::to_string_pretty`). 
Got result with missing `Machine` fields:
```
"[[activity]]\nname = \"TOML FTW\"\nproperty = 1\n"
```
Expected result (with `Machine` fields present):
```
"name = \"Sample text\"\n\n[[activity]]\nname = \"TOML FTW\"\nproperty = 1\n"
```
### Workaround
It works as expected if I drop `[machine]` definition in source toml.
[Link to playground](https://play.integer32.com/?version=stable&mode=debug&edition=2015&gist=c554fc6cff75493129d2edbaf8f00050)

**Comment by Nachasic** [comment]
I think it's an interesting issue specifically because modifying source toml fixes deserialization. No idea why, though

**Comment by tillulen** [comment]
(Please let me know if I misunderstand anything. I’m new to Rust and to TOML.)

It looks like that example is confusing the `[machine]` table and the root table of the TOML document.

To make sure we’re on the same page, here is my understanding of TOML structure.

```toml
# This `name` key is in the root table (root node) of the
# TOML document.
name = "foo"
```

```toml
# This TOML document has a single `machine` element in its root table.
# That element’s key is `machine` and its value is a table that contains a
# `name` element.
[machine]
name = "foo"
```

```toml
# Here we have both names.
name = "foo"

[machine]
name = "bar"
```

```toml
# This is equivalent to the previous snippet.
name = "foo"
machine.name = "bar"
```

Consider this [modified code](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=118aed573f96354e8a06d8f18e36585c). Does that make sense?

In the [original playground example](https://play.integer32.com/?version=stable&mode=debug&edition=2015&gist=c554fc6cff75493129d2edbaf8f00050), the code was expecting a `name` element in the root table but didn’t find any. The code was also ignoring the `[machine]` table entirely during parsing (the `Machine` struct actually corresponded to the root table, not the `[machine]` table). So the whole `[machine]` table couldn’t appear in the output later when the internal data structure was serialized.
