### ISSUE TITLE
No way to inline tables during serialization of array of tables

### ISSUE THREAD

**Issue by pshirshov** [toml-rs/toml-rs#406]
Both these toml docs are equivalent:

```toml
[[bins]]
name = 'native-image'

[bins.target]
type = 'Sdk'
name = 'jdk-graal'
```

```toml
[[bins]]
name = 'native-image'
target = { type =  'Sdk', name = 'jdk-graal' }
```

The second format is more compact and human-friendly. E.g. that's the default style of `cargo.toml`, promoted by all the docs.

Though seems like there is no way to get the second form by using `toml::to_string`. Though it can be parsed correctly.

Could you please add a way to use the second output format?
