### ISSUE TITLE
Add support for newlines and trailing commas in inline tables

### ISSUE THREAD

**Issue by oberien** [toml-rs/toml-rs#472]
The toml spec recently added support for allowing trailing commas and newlines in inline tables in https://github.com/toml-lang/toml/pull/904 fixing https://github.com/toml-lang/toml/issues/516. This allows code like the following:

```toml
contact = {
    personal = {
        name = "Donald Duck",
        email = "donald@duckburg.com",
    },
    work = {
        name = "Coin cleaner",
        email = "donald@ScroogeCorp.com",
    },
}
```
